# SPDX-FileCopyrightText: 2022-2024, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

[graph]
targets = [
  {triple = "x86_64-unknown-linux-gnu"},
  {triple = "x86_64-pc-windows-msvc"},
]

[advisories]
ignore = []

[licenses]
# The lint level for crates which do not have a detectable license
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "BSL-1.0",
  "Zlib",
  "ISC",
  "OFL-1.1",
  "Unicode-3.0",
]
confidence-threshold = 0.93
exceptions = [
  {allow = ["Unicode-DFS-2016"], name = "unicode-ident"}, # Unicode data
  {allow = ["LicenseRef-UFL-1.0"], name = "epaint_default_fonts"}, # Ubuntu font, sigh. https://ubuntu.com/legal/font-licence/faq
  {allow = ["MPL-2.0"], name = "option-ext"}, # file level copyleft OK
]

[bans]
# Lint level for when multiple versions of the same crate are detectedignore
# Default is warn, but there are too many of thse right now
multiple-versions = "allow"
# Lint level for when a crate version requirement is `*`
wildcards = "warn"



[[bans.deny]]
# These ship a precompiled binary blob instead of source
name = "serde_derive"
version = ">=1.0.172, <1.0.184"
