
# cargo-vet audits file

[[audits.block-buffer]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "0.10.3 -> 0.10.4"
notes = "Fixes a soundness error."

[[audits.emath]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "0.19.0 -> 0.21.0"
notes = "Only additional algorithm and simple, safe data structure added."

[[audits.futures-io]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "0.3.28 -> 0.3.30"
notes = "No change in this crate for these two releases."

[[audits.futures-sink]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "0.3.28 -> 0.3.30"
notes = "No changes in this crate for these two releases."

[[audits.instant]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-run"
version = "0.1.12"
notes = """
checked_add() and checked_sub() on SystemTime both fail to actually check,
but only float weirdness may result.
"""

[[audits.iswow64]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = """
Simple wrapper around Win32 API, that looks correct
according to the Microsoft documentation.
"""

[[audits.rustversion]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "1.0.9 -> 1.0.12"
notes = "Changes only affect documentation and build process dependencies."

[[audits.serde_derive]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "1.0.198 -> 1.0.200"
notes = "No functional change in this crate."

[[audits.special-folder]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
version = "0.2.2"
notes = """
Simple wrapper around Win32 API, that looks correct
according to the Microsoft documentation.
"""

[[audits.unicode-ident]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "1.0.6 -> 1.0.8"
notes = "Changes only affect documentation."

[[audits.winapi-build]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
version = "0.1.1"
notes = "Utilities for passing link arguments to rustc in build.rs files. Innocuous."

[[audits.windows-targets]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "0.42.1 -> 0.42.2"
notes = "Only patch updates to dependencies."

[[audits.windows-targets]]
who = "Rylie Pavlik <rylie.pavlik@collabora.com>"
criteria = "safe-to-deploy"
delta = "0.42.1 -> 0.42.2"
notes = "Only patch updates to dependencies."

[[trusted.windows]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-01-15"
end = "2025-05-07"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2025-05-07"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-05-07"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2025-05-07"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-05-07"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2025-05-07"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-05-07"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-05-07"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-05-07"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-05-07"
